### ISSUE TITLE
1.19.3 Version?

### ISSUE THREAD

**Issue by ExiledLizard** [sootysplash/informational-name-tags#1]
Hey, @sootysplash, I recently scrolled through the pages of Modrinth, and I saw your mod: "Informational Name Tags". I thought it was a cool mod, but I use the 1.19.3 version of the Minecraft Client, so I can't run it. So, my request is: can you make a 1.19.3 version of the mod?

**Comment by sootysplash** [comment]
https://modrinth.com/mod/info-name-tags/version/1.0.1
